import type { Post } from '../../types/models'

export const baseMockPosts: Post[] = [
  {
    id: 'post_1',
    authorId: 'franklin',
    authorName: '富兰克林',
    verifiedLabel: '雷电研究者 / 避雷针思想提出者',
    yearLabel: '1752',
    yearSort: 1752,
    title: '我发现雷电和电可能是同一种力量',
    content: `今天的实验有点刺激。我一直认为，天空中的雷电并不是神秘力量，而可能和实验室中的电现象本质相同。通过风筝、金属钥匙和导线等实验设计，我尝试证明雷雨天气中的电现象。这个发现的重要意义在于：人类开始用科学方法解释自然界中最令人敬畏的力量之一。后来，避雷针的思想也由此产生，它可以把雷电安全引入地下，保护建筑物和人的生命安全。电气工程的起点，不只是制造机器，而是人类第一次尝试理解并控制自然之电。`,
    tags: ['#雷电也是电', '#避雷针', '#自然电现象', '#电气工程起点'],
    likes: 652,
    commentsCount: 4,
    reposts: 118,
    favorites: 403,
    relatedInventionIds: ['invention_lightning_rod'],
    createdAt: '1752-06-15T09:00:00.000Z',
    comments: [
      {
        id: 'post_1_comment_1',
        authorId: 'volta',
        content: '大佬你先别放风筝了，我准备搞一个更稳定的电源。',
        createdAt: '1752-06-15T10:00:00.000Z',
      },
      {
        id: 'post_1_comment_2',
        authorId: 'faraday',
        content: '你证明了天空有电，我以后试试看能不能让机器发电。',
        createdAt: '1752-06-15T10:30:00.000Z',
      },
      {
        id: 'post_1_comment_3',
        authorId: 'modern_student_xiaoming',
        content: '这实验听起来有点猛，属于是拿命开题。',
        createdAt: '1752-06-15T11:10:00.000Z',
      },
      {
        id: 'post_1_comment_4',
        authorId: 'ta_assistant',
        content: '实验精神值得学习，但现实中请不要模仿危险实验。',
        createdAt: '1752-06-15T12:00:00.000Z',
      },
    ],
  },
  {
    id: 'post_2',
    authorId: 'volta',
    authorName: '伏打',
    verifiedLabel: '伏打电堆发明者 / 电池先驱',
    yearLabel: '1800',
    yearSort: 1800,
    title: '我做出了能够持续供电的伏打电堆',
    content: `今天正式发布我的新装置：伏打电堆。它由不同金属片和浸有盐水的材料交替叠放而成，可以持续产生电流。在此之前，人们更多研究的是静电，静电虽然能产生火花，但不稳定、不持久，很难支撑连续实验。伏打电堆的出现，使科学家第一次拥有了较稳定的电源。稳定电流的产生，推动了电化学、电磁实验、电报、电机等后续技术的发展。可以说，从这一刻开始，电不再只是瞬间闪现的自然现象，而成为可以被持续使用的能量。`,
    tags: ['#伏打电堆', '#稳定电流', '#电池起源', '#从静电到电流'],
    likes: 704,
    commentsCount: 4,
    reposts: 132,
    favorites: 451,
    relatedInventionIds: ['invention_voltaic_pile'],
    createdAt: '1800-03-20T08:30:00.000Z',
    comments: [
      {
        id: 'post_2_comment_1',
        authorId: 'franklin',
        content: '你这个比我的风筝安全多了。',
        createdAt: '1800-03-20T09:00:00.000Z',
      },
      {
        id: 'post_2_comment_2',
        authorId: 'oersted',
        content: '有稳定电流了？那我可以拿小磁针试试。',
        createdAt: '1800-03-20T09:20:00.000Z',
      },
      {
        id: 'post_2_comment_3',
        authorId: 'lithium_battery_modern',
        content: '祖师爷好，我现在已经进化到新能源汽车里了。',
        createdAt: '1800-03-20T10:00:00.000Z',
      },
      {
        id: 'post_2_comment_4',
        authorId: 'student_user',
        content: '原来电池最早是科学实验神器，不只是给手机续命的。',
        createdAt: '1800-03-20T10:50:00.000Z',
      },
    ],
  },
  {
    id: 'post_3',
    authorId: 'oersted',
    authorName: '奥斯特',
    verifiedLabel: '电流磁效应发现者',
    yearLabel: '1820',
    yearSort: 1820,
    title: '电流竟然能让磁针偏转',
    content: `今天课堂实验中出现了一个非常关键的现象：当导线中有电流通过时，附近的小磁针发生了偏转。这说明电流不仅仅在导线中流动，它还会在周围空间产生磁效应。过去，电学和磁学像是两个不同的领域：电学研究电荷和电流，磁学研究磁石和指南针。但现在，我们看到了电与磁之间的桥梁。这个发现为电磁铁、电动机、继电器、发电机以及整个电磁学理论的发展奠定了基础。磁针偏转的那一刻，人类科学史的方向也跟着转了。`,
    researchSteps: [
      {
        title: '灵感由来',
        content:
          '我在讲授电学实验时反复思考一个问题：如果电流只是“在线里流动”，为什么它不能影响线外世界？既然磁石可以让磁针转动，那么通电导线是否也可能产生类似作用？这个直觉来自“电与磁可能并非完全分离”的长期怀疑。',
      },
      {
        title: '研究思路',
        content:
          '核心思路是构造最小可观测系统：导线、稳定电流源、磁针。只要在控制好外部干扰后仍能稳定观测到偏转，就能证明“电流周围存在可感知磁效应”。',
      },
      {
        title: '实验内容',
        content:
          '将一根直导线平行放置于小磁针上方，先在断电状态记录磁针自然指向；再通电观察偏转方向与偏转角度；随后反向电流，比较偏转是否反向；最后改变导线与磁针距离，记录偏转变化趋势。',
      },
      {
        title: '实验方法',
        content:
          '采用“单变量控制”方式：每次只改变一个因素（电流方向、导线距离、电流大小）。每组至少重复多次，确认偏转具有可重复性。为降低偶然误差，先远离强磁性物体并保持台面水平。',
      },
      {
        title: '结论得出',
        content:
          '实验表明：只要导线中有电流，磁针就会偏转；电流方向反向，偏转方向也反向；距离越远，偏转越弱。由此可确认电流会在导线周围产生磁效应，电学与磁学存在本质联系。',
      },
    ],
    formulaDerivations: [
      {
        name: '电流元与磁场方向关系（概念式）',
        expression:
          '在同一观测点，单个电流元产生的磁场强度与电流大小和电流元长度成正比，与距离的三次方成反比，方向按右手关系确定。',
        derivation:
          '把导线拆成很多很短的小段，每一小段都会在观测点产生磁场贡献。电流越大、导线小段越长，贡献越大；观测点离导线越远，贡献衰减越快。把所有小段贡献按照方向叠加，就得到总磁场方向与大小。',
        note: '解释了“为什么反向电流会让磁针反向偏转”，并给出距离衰减直觉。',
      },
    ],
    tags: ['#电流磁效应', '#奥斯特实验', '#电磁学开端', '#磁针动了'],
    likes: 688,
    commentsCount: 4,
    reposts: 127,
    favorites: 438,
    relatedInventionIds: ['invention_electromagnetism_bridge'],
    createdAt: '1820-04-21T14:00:00.000Z',
    comments: [
      {
        id: 'post_3_comment_1',
        authorId: 'ampere',
        content: '收到，我马上研究电流之间到底怎么相互作用。',
        createdAt: '1820-04-21T14:30:00.000Z',
      },
      {
        id: 'post_3_comment_2',
        authorId: 'faraday',
        content: '你发现电能生磁，那我猜磁也许能生电。',
        createdAt: '1820-04-21T15:05:00.000Z',
      },
      {
        id: 'post_3_comment_3',
        authorId: 'compass_needle',
        content: '我只是轻轻一偏，没想到成了历史名场面。',
        createdAt: '1820-04-21T15:30:00.000Z',
      },
      {
        id: 'post_3_comment_4',
        authorId: 'modern_motor',
        content: '没有这一下，我可能还在娘胎里。',
        createdAt: '1820-04-21T16:10:00.000Z',
      },
    ],
  },
  {
    id: 'post_4',
    authorId: 'ampere',
    authorName: '安培',
    verifiedLabel: '电动力学奠基人',
    yearLabel: '1820',
    yearSort: 1820,
    title: '电流之间也会相互作用',
    content: `在奥斯特发现电流能够影响磁针之后，我继续研究电流之间的关系。我发现，两根通电导线之间会产生相互作用：当电流方向相同时，两根导线互相吸引；当电流方向相反时，它们互相排斥。这说明电流不只是产生磁效应，电流和电流之间也能通过磁场发生力的作用。这个发现对后来的电机理论非常重要。电动机能够转动，本质上就是利用电流在磁场中受到力的作用，实现电能向机械能的转换。电流不是孤独地流动，它会和其他电流隔空互动。`,
    researchSteps: [
      {
        title: '灵感由来',
        content:
          '奥斯特证明了“电流能影响磁针”，我进一步追问：如果磁针能受影响，那两根载流导线是否也会彼此施加作用力？',
      },
      {
        title: '研究思路',
        content:
          '搭建双导线系统，比较同向电流与反向电流两种工况下导线相对位移方向。通过“力学结果”反推电流-磁场-力之间的耦合关系。',
      },
      {
        title: '实验内容',
        content:
          '将两根平行导线悬挂并保持可微小位移，接入可调电流源。先同向通电观察是否靠近，再反向通电观察是否远离；逐步提高电流并记录位移幅度变化。',
      },
      {
        title: '实验方法',
        content:
          '采用差分观察：每组先记录断电零位，再记录通电位移，减少悬挂系统初始偏差。多轮重复并交换导线位置，排除结构不对称导致的假象。',
      },
      {
        title: '结论得出',
        content:
          '同向电流导线相吸，反向电流导线相斥，且作用强度随电流增大而增强。这是电动力学的关键证据，也为电机受力分析提供了可验证基础。',
      },
    ],
    formulaDerivations: [
      {
        name: '平行载流导线单位长度作用力',
        expression:
          '两根平行导线每单位长度的作用力，等于真空磁导率乘以两导线电流，再除以二乘圆周率与导线间距的乘积。',
        derivation:
          '先计算导线一在导线二位置产生的磁场强度：它与导线一电流成正比、与导线间距成反比。再把这个磁场代入安培力关系，得到导线二每单位长度受力大小。若两电流方向相同则吸引，方向相反则排斥。',
        note: '把“观察到的吸引/排斥”量化为可计算工程关系，是电机电磁力设计基础。',
      },
    ],
    tags: ['#安培定律', '#电动力学', '#电磁力', '#电机基础'],
    likes: 671,
    commentsCount: 4,
    reposts: 121,
    favorites: 420,
    relatedInventionIds: ['invention_electrodynamics'],
    createdAt: '1820-10-10T10:20:00.000Z',
    comments: [
      {
        id: 'post_4_comment_1',
        authorId: 'oersted',
        content: '我刚发现磁针会动，你直接开始研究力了，卷王。',
        createdAt: '1820-10-10T10:50:00.000Z',
      },
      {
        id: 'post_4_comment_2',
        authorId: 'faraday',
        content: '电能产生力，那发电机和电动机就有希望了。',
        createdAt: '1820-10-10T11:15:00.000Z',
      },
      {
        id: 'post_4_comment_3',
        authorId: 'motor',
        content: '收到理论支持，我以后负责转起来。',
        createdAt: '1820-10-10T11:50:00.000Z',
      },
      {
        id: 'post_4_comment_4',
        authorId: 'student_user',
        content: '原来电机不是靠玄学旋转，是电磁力在干活。',
        createdAt: '1820-10-10T12:30:00.000Z',
      },
    ],
  },
  {
    id: 'post_5',
    authorId: 'faraday',
    authorName: '法拉第',
    verifiedLabel: '电磁感应发现者 / 发电机理论奠基人',
    yearLabel: '1831',
    yearSort: 1831,
    title: '磁也能生电，我发现了电磁感应',
    content: `今天，我终于观察到一个极其重要的现象：当磁场发生变化时，导线中会产生电流。这就是电磁感应。此前，奥斯特证明了电流可以产生磁效应。我一直在思考：如果电能产生磁，那么磁能不能反过来产生电？经过多次实验，我发现只要磁场发生变化，或者导体切割磁感线，电路中就会出现感应电流。这个发现成为发电机的理论基础。未来，人们可以利用水轮机、蒸汽机、风轮等机械装置带动线圈或磁体运动，从而持续产生电能。如果说伏打给了科学家一股小电流，那么电磁感应将给未来城市一整片灯火。`,
    researchSteps: [
      {
        title: '灵感由来',
        content:
          '电生磁已经被证实，我始终相信自然规律应具备某种对称性：若电可生磁，磁应当也能生电。问题是触发条件到底是什么。',
      },
      {
        title: '研究思路',
        content:
          '不是观察“静止磁场是否生电”，而是测试“磁场变化是否生电”。所以设计动态实验：改变磁通量，而非只改变磁场存在与否。',
      },
      {
        title: '实验内容',
        content:
          '在线圈两端接检流计，分别进行三组操作：磁铁快速插入线圈、快速拔出线圈、保持磁铁静止。记录指针偏转方向与幅度，并比较运动速度变化对偏转幅度的影响。',
      },
      {
        title: '实验方法',
        content:
          '采用“动作-响应”时间对齐记录法：在同一器件上交替做插入/拔出/静止实验，控制除磁通变化外的其他变量。重复多次取一致结果，确认感应电流并非偶然噪声。',
      },
      {
        title: '结论得出',
        content:
          '只有磁通量发生变化才有感应电动势与感应电流；磁通不变则无持续电流。由此得到发电机核心机理：通过机械运动持续改变磁通，即可持续发电。',
      },
    ],
    formulaDerivations: [
      {
        name: '法拉第电磁感应定律',
        expression: '感应电动势等于线圈匝数乘以磁通量变化率，并带反向符号。',
        derivation:
          '实验显示感应效应大小取决于磁通量变化速度：变化越快，感应越强；磁通量不变化则无感应。把单匝效应扩展到多匝线圈后，感应电动势与匝数成正比。反向符号表示感应电流总是阻碍原有磁通变化趋势。',
        note: '直接给出提高发电能力的工程方向：增大匝数，提升单位时间内磁通量变化。',
      },
    ],
    tags: ['#电磁感应', '#法拉第', '#发电机基础', '#磁生电'],
    likes: 888,
    commentsCount: 4,
    reposts: 196,
    favorites: 611,
    relatedInventionIds: ['invention_electromagnetic_induction', 'invention_generator'],
    createdAt: '1831-08-29T13:00:00.000Z',
    comments: [
      {
        id: 'post_5_comment_1',
        authorId: 'oersted',
        content: '我发现电生磁，你完成磁生电，闭环了。',
        createdAt: '1831-08-29T13:30:00.000Z',
      },
      {
        id: 'post_5_comment_2',
        authorId: 'maxwell',
        content: '实验很强，接下来我来写方程。',
        createdAt: '1831-08-29T14:05:00.000Z',
      },
      {
        id: 'post_5_comment_3',
        authorId: 'power_plant_official',
        content: '祖师爷好，我的工作原理就是您给的。',
        createdAt: '1831-08-29T14:40:00.000Z',
      },
      {
        id: 'post_5_comment_4',
        authorId: 'student_user',
        content: '这一条应该置顶，电气工程史的超级大招。',
        createdAt: '1831-08-29T15:20:00.000Z',
      },
    ],
  },
  {
    id: 'post_6',
    authorId: 'maxwell',
    authorName: '麦克斯韦',
    verifiedLabel: '电磁理论统一者',
    yearLabel: '1860',
    yearSort: 1860,
    title: '我把电和磁统一写进了方程',
    content: `前人的实验已经证明，电和磁不是孤立的现象。富兰克林研究自然电，奥斯特发现电流产生磁，法拉第发现变化的磁场产生电流。现在，我尝试把这些规律统一到一个理论体系中。电磁理论说明：变化的电场可以产生磁场，变化的磁场也可以产生电场。电场和磁场能够相互激发，并在空间中传播，这种传播形式就是电磁波。更重要的是，电磁波的传播速度接近光速，因此光本身也可以理解为一种电磁波。麦克斯韦方程组为无线通信、雷达、微波技术、天线设计、光通信和现代电子信息技术奠定了理论基础。`,
    tags: ['#麦克斯韦方程组', '#电磁波', '#光也是电磁波', '#理论统一'],
    likes: 936,
    commentsCount: 4,
    reposts: 210,
    favorites: 658,
    relatedInventionIds: ['invention_maxwell_equations'],
    createdAt: '1860-05-01T09:30:00.000Z',
    comments: [
      {
        id: 'post_6_comment_1',
        authorId: 'faraday',
        content: '我数学不太强，但你真的把我的实验升华了。',
        createdAt: '1860-05-01T10:00:00.000Z',
      },
      {
        id: 'post_6_comment_2',
        authorId: 'hertz',
        content: '收到预言，我去实验室验证一下。',
        createdAt: '1860-05-01T10:40:00.000Z',
      },
      {
        id: 'post_6_comment_3',
        authorId: 'wireless_comm',
        content: '感谢理论地基，没有你我发不出去信号。',
        createdAt: '1860-05-01T11:10:00.000Z',
      },
      {
        id: 'post_6_comment_4',
        authorId: 'student_user',
        content: '方程一出，物理世界突然开始排队。',
        createdAt: '1860-05-01T11:50:00.000Z',
      },
    ],
  },
  {
    id: 'post_7',
    authorId: 'hertz',
    authorName: '赫兹',
    verifiedLabel: '电磁波实验证实者',
    yearLabel: '1887',
    yearSort: 1887,
    title: '电磁波真的存在',
    content: `麦克斯韦曾经从理论上预言电磁波的存在。今天，我通过实验观察到了电磁波的产生、传播和接收。在实验中，我利用振荡电路产生高频电磁振荡，并在远处的接收装置上观察到了电火花现象。这说明电磁波确实可以脱离导线，在空间中传播。这个发现意义重大，因为它证明麦克斯韦的理论不仅是漂亮的数学形式，更是真实存在的自然规律。未来，人们可以利用电磁波进行无线通信，不再完全依赖电缆和导线。从这一刻起，信息传播开始具备飞越空间的可能。`,
    tags: ['#赫兹实验', '#电磁波存在', '#无线通信基础', '#麦克斯韦预言成真'],
    likes: 823,
    commentsCount: 4,
    reposts: 174,
    favorites: 539,
    relatedInventionIds: ['invention_radio_wave_validation'],
    createdAt: '1887-11-13T15:00:00.000Z',
    comments: [
      {
        id: 'post_7_comment_1',
        authorId: 'maxwell',
        content: '谢谢验证，理论党今天很欣慰。',
        createdAt: '1887-11-13T15:40:00.000Z',
      },
      {
        id: 'post_7_comment_2',
        authorId: 'marconi',
        content: '无线通信？我马上安排。',
        createdAt: '1887-11-13T16:10:00.000Z',
      },
      {
        id: 'post_7_comment_3',
        authorId: 'wifi_official',
        content: '爷爷好，我现在每天都在空气里跑数据。',
        createdAt: '1887-11-13T16:50:00.000Z',
      },
      {
        id: 'post_7_comment_4',
        authorId: 'student_user',
        content: '原来 Hz 这个单位真的是人名来的。',
        createdAt: '1887-11-13T17:30:00.000Z',
      },
    ],
  },
  {
    id: 'post_8',
    authorId: 'morse',
    authorName: '莫尔斯',
    verifiedLabel: '电报系统推动者 / 莫尔斯电码发明者',
    yearLabel: '1844',
    yearSort: 1844,
    title: '我让信息沿着电线跑起来',
    content: `今天我要介绍一种新的远距离通信方式：电报。通过电信号的通断变化，我们可以把文字信息编码成点和划，再沿着导线传送到远方。过去，信息传播依靠人、马车、船只和书信，速度受交通条件限制。而电报让信息第一次接近瞬时传输。一个城市发生的消息，可以在很短时间内传到另一个城市。电报的意义不只是通信技术进步，它改变了新闻、商业、军事、铁路调度和国家管理方式。电气工程在这里完成了一次重要扩展：它不只传输能量，也开始传输信息。`,
    tags: ['#电报', '#莫尔斯电码', '#信息传输', '#通信工程起点'],
    likes: 745,
    commentsCount: 4,
    reposts: 143,
    favorites: 462,
    relatedInventionIds: ['invention_telegraph'],
    createdAt: '1844-05-24T08:00:00.000Z',
    comments: [
      {
        id: 'post_8_comment_1',
        authorId: 'bell',
        content: '文字能传，声音应该也能传。',
        createdAt: '1844-05-24T08:40:00.000Z',
      },
      {
        id: 'post_8_comment_2',
        authorId: 'marconi',
        content: '有线很强，但我想试试无线。',
        createdAt: '1844-05-24T09:15:00.000Z',
      },
      {
        id: 'post_8_comment_3',
        authorId: 'student_user',
        content: '这不就是古早版微信消息吗？',
        createdAt: '1844-05-24T09:50:00.000Z',
      },
      {
        id: 'post_8_comment_4',
        authorId: 'rail_dispatcher',
        content: '终于不用靠吼和跑腿了。',
        createdAt: '1844-05-24T10:30:00.000Z',
      },
    ],
  },
  {
    id: 'post_9',
    authorId: 'bell',
    authorName: '贝尔',
    verifiedLabel: '电话发明者',
    yearLabel: '1876',
    yearSort: 1876,
    title: '声音可以通过电传出去',
    content: `今天，我成功实现了声音的电传输。通过把声音振动转换为电信号，再在远处还原成声音，人类可以不依靠面对面交流，也能听到对方说话。电报解决的是文字通信问题，而电话解决的是声音通信问题。声音比文字更直接，也更有实时性和情感表达能力。电话的出现，使电信网络逐渐走进家庭、办公室和城市管理系统。它也推动了信号传输、交换网络、线路建设和通信工程的发展。从这一刻开始，电气工程不只是点亮城市，也开始连接人类的声音。`,
    tags: ['#电话', '#语音通信', '#电信网络', '#声音变成电信号'],
    likes: 796,
    commentsCount: 4,
    reposts: 158,
    favorites: 507,
    relatedInventionIds: ['invention_telephone'],
    createdAt: '1876-03-10T10:00:00.000Z',
    comments: [
      {
        id: 'post_9_comment_1',
        authorId: 'morse',
        content: '文字之后轮到声音了。',
        createdAt: '1876-03-10T10:45:00.000Z',
      },
      {
        id: 'post_9_comment_2',
        authorId: 'smartphone_modern',
        content: '祖师爷，我现在不仅能打电话，还能刷短视频。',
        createdAt: '1876-03-10T11:20:00.000Z',
      },
      {
        id: 'post_9_comment_3',
        authorId: 'student_user',
        content: '所以麦克风和扬声器本质上也和电磁转换有关？懂了。',
        createdAt: '1876-03-10T11:55:00.000Z',
      },
      {
        id: 'post_9_comment_4',
        authorId: 'introvert_user',
        content: '技术很好，但我还是喜欢发消息。',
        createdAt: '1876-03-10T12:40:00.000Z',
      },
    ],
  },
  {
    id: 'post_10',
    authorId: 'edison',
    authorName: '爱迪生',
    verifiedLabel: '电灯与直流供电系统推广者',
    yearLabel: '1879',
    yearSort: 1879,
    title: '我想把电灯送进城市',
    content: `今天我想宣布：电灯不应该只停留在实验室，它应该进入城市、街道、工厂和家庭。经过大量试验，我们改进了白炽灯，使它具备更好的寿命和实用性。但只有电灯本身还不够，真正重要的是建立完整的供电系统：发电站、输电线路、开关、保险装置、电表和用户终端都必须配套。1882 年，纽约珍珠街电站投入运行，向附近用户提供直流电。这是城市电气化的重要尝试。电气工程从这里开始变成一个系统工程，而不是单个发明。我的目标不是制造一盏灯，而是建立一个能让千家万户同时亮起来的电力网络。`,
    tags: ['#白炽灯', '#珍珠街电站', '#城市电气化', '#直流供电'],
    likes: 892,
    commentsCount: 4,
    reposts: 182,
    favorites: 566,
    relatedInventionIds: ['invention_incandescent_lamp', 'invention_dc_power_system'],
    createdAt: '1879-10-21T18:00:00.000Z',
    comments: [
      {
        id: 'post_10_comment_1',
        authorId: 'franklin',
        content: '以前我们研究雷电，现在你把夜晚点亮了。',
        createdAt: '1879-10-21T18:40:00.000Z',
      },
      {
        id: 'post_10_comment_2',
        authorId: 'tesla',
        content: '灯不错，但远距离输电还是交流更适合。',
        createdAt: '1879-10-21T19:15:00.000Z',
      },
      {
        id: 'post_10_comment_3',
        authorId: 'city_resident',
        content: '晚上终于不是黑黢黢一片了。',
        createdAt: '1879-10-21T19:50:00.000Z',
      },
      {
        id: 'post_10_comment_4',
        authorId: 'electric_bill',
        content: '我也从此诞生了，嘿嘿。',
        createdAt: '1879-10-21T20:20:00.000Z',
      },
    ],
  },
  {
    id: 'post_11',
    authorId: 'tesla',
    authorName: '特斯拉',
    verifiedLabel: '交流电系统与感应电机推动者',
    yearLabel: '1888',
    yearSort: 1888,
    title: '交流电系统才适合远方',
    content: `直流电可以在局部范围内供电，但如果要让电能跨越更远距离，就需要更灵活的系统。我支持交流电，因为交流电可以通过变压器方便地升压和降压。升高电压可以降低输电过程中的损耗，到了用户端再降压使用。这使远距离、大规模输电成为可能。与此同时，交流感应电机也为工业动力提供了可靠方案。交流电的意义不只是换了一种电流形式，而是让电力系统从局部照明网络扩展成跨区域能源网络。未来城市、工厂、铁路和家庭都可以被连接到更大的电网之中。电不应该只在附近流动，它应该去远方。`,
    tags: ['#交流电', '#感应电机', '#远距离输电', '#电流大战'],
    likes: 975,
    commentsCount: 4,
    reposts: 231,
    favorites: 690,
    relatedInventionIds: ['invention_ac_power_system', 'invention_transformer_network'],
    createdAt: '1888-05-16T10:00:00.000Z',
    comments: [
      {
        id: 'post_11_comment_1',
        authorId: 'edison',
        content: '你小子又来拆我直流台了。',
        createdAt: '1888-05-16T10:35:00.000Z',
      },
      {
        id: 'post_11_comment_2',
        authorId: 'westinghouse',
        content: '放心，我负责把交流系统推向工程应用。',
        createdAt: '1888-05-16T11:10:00.000Z',
      },
      {
        id: 'post_11_comment_3',
        authorId: 'transformer',
        content: '终于有人懂我了，升压降压交给我。',
        createdAt: '1888-05-16T11:50:00.000Z',
      },
      {
        id: 'post_11_comment_4',
        authorId: 'hvdc_modern',
        content: '没有交流系统，电网规模很难做大。',
        createdAt: '1888-05-16T12:30:00.000Z',
      },
    ],
  },
  {
    id: 'post_12',
    authorId: 'westinghouse',
    authorName: '威斯汀豪斯',
    verifiedLabel: '交流电商业化推动者',
    yearLabel: '1895',
    yearSort: 1895,
    title: '交流电要进入大型工程',
    content: `技术不仅要在实验室成立，还要在真实工程中稳定运行。交流电系统的优势在大型电力工程中逐渐显现：它可以升压输送、降压使用，更适合远距离、大容量电力传输。尼亚加拉瀑布水电工程是一个重要标志。工程利用水力带动发电设备，再通过交流输电系统把电能送往远方。这证明了交流电不仅在理论上可行，而且在大规模工程中具有巨大优势。电气工程的发展从来不是某个天才单独完成的。科学原理、发明设计、商业推广和工程建设必须结合起来，才能真正改变社会。`,
    tags: ['#尼亚加拉水电站', '#交流输电', '#电力工程', '#从实验到产业'],
    likes: 861,
    commentsCount: 4,
    reposts: 169,
    favorites: 544,
    relatedInventionIds: ['invention_niagara_project', 'invention_ac_power_system'],
    createdAt: '1895-11-16T08:40:00.000Z',
    comments: [
      {
        id: 'post_12_comment_1',
        authorId: 'tesla',
        content: '交流系统终于上大工程了。',
        createdAt: '1895-11-16T09:15:00.000Z',
      },
      {
        id: 'post_12_comment_2',
        authorId: 'edison',
        content: '行吧，这局你们确实赢得漂亮。',
        createdAt: '1895-11-16T09:45:00.000Z',
      },
      {
        id: 'post_12_comment_3',
        authorId: 'water_turbine',
        content: '我负责转，你们负责把电送出去。',
        createdAt: '1895-11-16T10:20:00.000Z',
      },
      {
        id: 'post_12_comment_4',
        authorId: 'modern_grid',
        content: '祖上已经开始搞大规模联网了。',
        createdAt: '1895-11-16T11:00:00.000Z',
      },
    ],
  },
  {
    id: 'post_13',
    authorId: 'marconi',
    authorName: '马可尼',
    verifiedLabel: '无线电通信推动者',
    yearLabel: '1895',
    yearSort: 1895,
    title: '信息可以不用导线',
    content: `赫兹已经证明电磁波真实存在。现在，我尝试把这种现象用于通信。通过发射和接收无线电波，信息可以不依赖导线，在空间中传播。这项技术对航海、军事、新闻传播和远距离通信意义重大。船只在海上也能发送求救信号，遥远地区之间的信息交流更加方便。无线电通信说明，电气工程已经进入看不见的空间。电不只在导线中流动，信号也可以通过电磁波穿越空气、海洋和大陆。未来，人类的信息网络将不仅仅依靠电缆，还会布满天空。`,
    tags: ['#无线电', '#电磁波通信', '#马可尼', '#无导线信息传输'],
    likes: 905,
    commentsCount: 4,
    reposts: 194,
    favorites: 580,
    relatedInventionIds: ['invention_radio_communication'],
    createdAt: '1895-12-10T13:20:00.000Z',
    comments: [
      {
        id: 'post_13_comment_1',
        authorId: 'hertz',
        content: '我验证电磁波，你拿去发消息，很会用。',
        createdAt: '1895-12-10T14:00:00.000Z',
      },
      {
        id: 'post_13_comment_2',
        authorId: 'wifi_official',
        content: '我每天都在继承你的事业。',
        createdAt: '1895-12-10T14:35:00.000Z',
      },
      {
        id: 'post_13_comment_3',
        authorId: 'mobile_communication',
        content: '从无线电到 5G，空气越来越忙了。',
        createdAt: '1895-12-10T15:10:00.000Z',
      },
      {
        id: 'post_13_comment_4',
        authorId: 'electromagnetic_wave',
        content: '别挤别挤，大家都在我身上发数据。',
        createdAt: '1895-12-10T15:55:00.000Z',
      },
    ],
  },
  {
    id: 'post_14',
    authorId: 'de_forest',
    authorName: '德福雷斯特',
    verifiedLabel: '三极管电子管发明者 / 电子工程先驱',
    yearLabel: '1906',
    yearSort: 1906,
    title: '我让电信号变强了',
    content: `今天我要介绍一种重要器件：三极管电子管。它可以对微弱电信号进行放大，也可以用于振荡、调制和控制。在通信系统中，信号经过长距离传输后会变弱。如果不能放大，远距离语音和无线电通信就会受到严重限制。电子管的出现，使电信号处理能力大大增强。这意味着电气工程从传输电能和信息，进一步发展到主动控制和处理信号。无线电广播、电话通信、雷达、电视和早期计算机都将受益于电子管技术。电气工程从此进入电子工程时代。`,
    tags: ['#电子管', '#信号放大', '#电子工程', '#广播雷达计算机'],
    likes: 782,
    commentsCount: 4,
    reposts: 152,
    favorites: 495,
    relatedInventionIds: ['invention_vacuum_tube'],
    createdAt: '1906-12-24T09:10:00.000Z',
    comments: [
      {
        id: 'post_14_comment_1',
        authorId: 'bell',
        content: '信号变强了，电话网络更有希望了。',
        createdAt: '1906-12-24T09:45:00.000Z',
      },
      {
        id: 'post_14_comment_2',
        authorId: 'marconi',
        content: '无线电通信需要你这种放大能力。',
        createdAt: '1906-12-24T10:15:00.000Z',
      },
      {
        id: 'post_14_comment_3',
        authorId: 'transistor_entity',
        content: '前辈辛苦了，后面小型化交给我。',
        createdAt: '1906-12-24T10:50:00.000Z',
      },
      {
        id: 'post_14_comment_4',
        authorId: 'early_computer',
        content: '虽然我很大很热，但我能算。',
        createdAt: '1906-12-24T11:30:00.000Z',
      },
    ],
  },
  {
    id: 'post_15',
    authorId: 'bell_labs',
    authorName: '贝尔实验室',
    verifiedLabel: '晶体管诞生地 / 半导体技术推动者',
    yearLabel: '1947',
    yearSort: 1947,
    title: '晶体管诞生了',
    content: `今天，我们发布一项可能改变电子技术未来的成果：晶体管。相比电子管，晶体管体积更小、功耗更低、可靠性更高、寿命更长。它可以实现信号放大和开关控制，是现代电子设备的核心基础。晶体管的意义远远超过一个器件本身。大量晶体管可以组成复杂电路，进一步发展出集成电路、微处理器、计算机、手机、互联网设备和人工智能硬件。从电气工程的角度看，晶体管让人类对电信号的控制进入微观尺度。过去我们用电点亮城市，现在我们开始用电构建计算与智能。`,
    tags: ['#晶体管', '#贝尔实验室', '#半导体革命', '#信息时代基石'],
    likes: 1120,
    commentsCount: 4,
    reposts: 265,
    favorites: 809,
    relatedInventionIds: ['invention_transistor'],
    createdAt: '1947-12-16T16:00:00.000Z',
    comments: [
      {
        id: 'post_15_comment_1',
        authorId: 'de_forest',
        content: '年轻人你很小，但确实很强。',
        createdAt: '1947-12-16T16:35:00.000Z',
      },
      {
        id: 'post_15_comment_2',
        authorId: 'integrated_circuit',
        content: '等我把你们成千上万个装到一块芯片上。',
        createdAt: '1947-12-16T17:10:00.000Z',
      },
      {
        id: 'post_15_comment_3',
        authorId: 'smartphone_modern',
        content: '没有晶体管，我就是一块漂亮板砖。',
        createdAt: '1947-12-16T17:40:00.000Z',
      },
      {
        id: 'post_15_comment_4',
        authorId: 'cpu',
        content: '我的身体里全是这位祖宗的后代。',
        createdAt: '1947-12-16T18:20:00.000Z',
      },
    ],
  },
  {
    id: 'post_16',
    authorId: 'integrated_circuit_ic',
    authorName: '集成电路IC',
    verifiedLabel: '芯片时代代表技术',
    yearLabel: '1958',
    yearSort: 1958,
    title: '我把电路装进芯片里',
    content: `晶体管已经证明了小型电子器件的巨大价值。但如果每个晶体管、电阻、电容都要单独连接，复杂系统仍然会庞大、昂贵且不可靠。集成电路的思路是：把多个电子元件和连接线路集成在同一块半导体材料上。这样，电路可以变得更小、更快、更稳定，也更适合大规模生产。集成电路让电子系统从分立元件拼装进入芯片化集成时代。计算机、通信设备、自动控制系统、航天电子、消费电子都因此发生巨大变化。电气工程到这里已经深入到微观器件、芯片设计和信息处理之中。`,
    tags: ['#集成电路', '#芯片', '#微电子', '#从晶体管到计算机'],
    likes: 1096,
    commentsCount: 4,
    reposts: 251,
    favorites: 773,
    relatedInventionIds: ['invention_integrated_circuit'],
    createdAt: '1958-09-12T11:30:00.000Z',
    comments: [
      {
        id: 'post_16_comment_1',
        authorId: 'transistor_entity',
        content: '我被集体安排进芯片了。',
        createdAt: '1958-09-12T12:00:00.000Z',
      },
      {
        id: 'post_16_comment_2',
        authorId: 'computer',
        content: '终于可以变小一点了，不然房间都装不下我。',
        createdAt: '1958-09-12T12:35:00.000Z',
      },
      {
        id: 'post_16_comment_3',
        authorId: 'artificial_intelligence',
        content: '没有芯片，我只能在纸上幻想。',
        createdAt: '1958-09-12T13:05:00.000Z',
      },
      {
        id: 'post_16_comment_4',
        authorId: 'semiconductor_fab',
        content: '欢迎来到精密制造地狱副本。',
        createdAt: '1958-09-12T13:45:00.000Z',
      },
    ],
  },
  {
    id: 'post_17',
    authorId: 'plc_controller',
    authorName: 'PLC控制器',
    verifiedLabel: '工业自动化核心设备',
    yearLabel: '1968',
    yearSort: 1968,
    title: '工厂开始自动运行',
    content: `以前的工业控制大量依靠继电器线路。线路复杂，修改困难，维护成本高。现在，可编程逻辑控制器，也就是 PLC，开始进入工厂。PLC 可以根据程序控制电机、传感器、阀门、机械臂和生产设备，实现稳定、可靠的工业自动化控制。它让工厂从人工操作为主逐渐变成程序控制为主。这代表电气工程进一步和自动控制、计算机技术结合。电气系统不再只是供电和驱动设备，还要感知状态、执行逻辑、做出控制决策。现代生产线、楼宇控制、交通系统、电梯系统和智能制造，都离不开自动控制技术。`,
    tags: ['#PLC', '#自动控制', '#工业自动化', '#智能制造基础'],
    likes: 864,
    commentsCount: 4,
    reposts: 176,
    favorites: 542,
    relatedInventionIds: ['invention_plc'],
    createdAt: '1968-06-01T08:10:00.000Z',
    comments: [
      {
        id: 'post_17_comment_1',
        authorId: 'motor',
        content: '以前我只负责转，现在还要听程序指挥。',
        createdAt: '1968-06-01T08:45:00.000Z',
      },
      {
        id: 'post_17_comment_2',
        authorId: 'sensor',
        content: '我负责告诉系统现场发生了什么。',
        createdAt: '1968-06-01T09:20:00.000Z',
      },
      {
        id: 'post_17_comment_3',
        authorId: 'modern_factory',
        content: '没有 PLC，我可能忙到冒烟。',
        createdAt: '1968-06-01T09:55:00.000Z',
      },
      {
        id: 'post_17_comment_4',
        authorId: 'relay',
        content: '虽然我老了，但我也曾经辉煌过。',
        createdAt: '1968-06-01T10:25:00.000Z',
      },
    ],
  },
  {
    id: 'post_18',
    authorId: 'power_electronics',
    authorName: '电力电子技术',
    verifiedLabel: '电能变换与控制核心技术',
    yearLabel: '1970',
    yearSort: 1970,
    title: '电能也可以被精细控制',
    content: `传统电力系统擅长发电、输电和配电，但现代社会需要更灵活地控制电能。我们需要改变电压、电流、频率和波形，让电能适应不同设备和场景。电力电子技术利用功率半导体器件实现电能变换。例如，整流可以把交流变成直流，逆变可以把直流变成交流，变频可以改变电机转速，开关电源可以高效供电。这项技术广泛应用于新能源汽车、高铁牵引、光伏逆变器、风电并网、变频空调、工业机器人和数据中心电源。如果说传统电网负责送电，那么电力电子负责让电变得听话。`,
    tags: ['#电力电子', '#整流逆变', '#变频器', '#新能源并网'],
    likes: 934,
    commentsCount: 4,
    reposts: 205,
    favorites: 617,
    relatedInventionIds: ['invention_power_electronics'],
    createdAt: '1970-01-20T09:15:00.000Z',
    comments: [
      {
        id: 'post_18_comment_1',
        authorId: 'tesla',
        content: '交流和直流终于可以灵活转换了。',
        createdAt: '1970-01-20T09:50:00.000Z',
      },
      {
        id: 'post_18_comment_2',
        authorId: 'ev_vehicle',
        content: '没有你，我跑不起来。',
        createdAt: '1970-01-20T10:20:00.000Z',
      },
      {
        id: 'post_18_comment_3',
        authorId: 'photovoltaic',
        content: '我发的是直流，并网还得靠逆变器。',
        createdAt: '1970-01-20T10:55:00.000Z',
      },
      {
        id: 'post_18_comment_4',
        authorId: 'electric_energy',
        content: '以前我有点野，现在被安排得明明白白。',
        createdAt: '1970-01-20T11:35:00.000Z',
      },
    ],
  },
  {
    id: 'post_19',
    authorId: 'smart_grid',
    authorName: '智能电网',
    verifiedLabel: '现代能源系统大脑',
    yearLabel: '21世纪',
    yearSort: 2001,
    title: '我开始接入新能源、储能和 AI',
    content: `大家好，我是智能电网。我的祖先包括发电机、变压器、交流输电、电力电子、自动控制和通信系统。现在，我正在进入新能源和人工智能时代。传统电网主要面对稳定、可控的火电和水电。但现在，风电和光伏具有波动性，电动汽车、储能系统和分布式能源大量接入，电网必须变得更聪明。我需要实时感知负荷变化，预测发电情况，调度储能设备，协调充电桩，处理故障，并尽可能提高能源利用效率。人工智能、大数据、物联网和通信技术正在成为我的新工具。电气工程的未来，不只是把电送到用户家里，而是构建一个清洁、安全、高效、自我调节的能源网络。`,
    tags: ['#智能电网', '#新能源', '#储能', '#人工智能调度', '#能源互联网'],
    likes: 1268,
    commentsCount: 4,
    reposts: 308,
    favorites: 927,
    relatedInventionIds: ['invention_smart_grid'],
    createdAt: '2001-01-01T10:00:00.000Z',
    comments: [
      {
        id: 'post_19_comment_1',
        authorId: 'faraday',
        content: '看到这里，我的电磁感应没有白发现。',
        createdAt: '2001-01-01T10:40:00.000Z',
      },
      {
        id: 'post_19_comment_2',
        authorId: 'tesla',
        content: '远距离输电只是开始，你已经进化成系统大脑了。',
        createdAt: '2001-01-01T11:15:00.000Z',
      },
      {
        id: 'post_19_comment_3',
        authorId: 'power_electronics',
        content: '新能源并网这块，我必须在场。',
        createdAt: '2001-01-01T11:55:00.000Z',
      },
      {
        id: 'post_19_comment_4',
        authorId: 'franklin',
        content: '当年我只是放了个风筝，没想到你们玩这么大。',
        createdAt: '2001-01-01T12:30:00.000Z',
      },
    ],
  },
  {
    id: 'post_20',
    authorId: 'ohm',
    authorName: '欧姆',
    verifiedLabel: '欧姆定律提出者',
    yearLabel: '1827',
    yearSort: 1827,
    title: '我把电流、电压和电阻写成了可计算关系',
    content: `今天我想把一个看似朴素、但会长期影响工程实践的关系公开：在温度等条件稳定时，导体中的电流与两端电压成正比，与电阻成反比。也就是后来大家常写的 V = IR。它的意义不是“多了一个公式”，而是让电学从“描述现象”进入“可计算、可设计、可验证”的阶段。

在教学和工程里，这个关系可以直接回答很多问题：为什么同样电源接不同负载时电流不同？为什么导线太细会发热？为什么远距离输电要提高电压、降低电流以减少损耗？当我们能够定量分析后，电路设计就不再靠经验拍脑袋，而是可以基于指标做权衡。对后来的通信、电机、电子设备乃至电力系统而言，欧姆定律都像一把最早交到工程师手里的“标尺”。`,
    researchSteps: [
      {
        title: '灵感由来',
        content:
          '我想把“电学现象”从定性描述推进到定量规律：如果机械和光学都能通过公式预测，电学也应具备同样可计算性。',
      },
      {
        title: '研究思路',
        content:
          '在可控导体上分别改变外加电压与导体参数，测量稳态电流，检验三者间是否存在稳定函数关系。',
      },
      {
        title: '实验内容',
        content:
          '选取不同长度、截面积和材料的导体，施加多组电压，记录回路电流；再在相同导体上改变电压，观察电流线性变化区间。',
      },
      {
        title: '实验方法',
        content:
          '保持温度尽量恒定，采用重复测量取平均值以减小偶然误差。将测得数据绘制 I-U 曲线，检查是否近似直线并计算斜率差异。',
      },
      {
        title: '结论得出',
        content:
          '在给定导体和近似恒温条件下，电流与电压成正比；对不同导体，该比例系数不同，可定义为电阻。由此建立 V、I、R 三者关系。',
      },
    ],
    formulaDerivations: [
      {
        name: '欧姆定律',
        expression: '电压等于电流乘以电阻；等价地，电流等于电压除以电阻。',
        derivation:
          '实验曲线显示电流与电压近似线性关系。把比例系数定义为导体导电能力，再取其倒数定义为电阻，就得到“电压等于电流乘以电阻”的关系。在一定温度范围内，电阻可视为常量。',
        note: '成为电路设计、功率估算、器件选型与安全校核最基础的计算公式。',
      },
    ],
    tags: ['#欧姆定律', '#电阻', '#电路分析', '#工程可计算'],
    likes: 812,
    commentsCount: 4,
    reposts: 171,
    favorites: 559,
    relatedInventionIds: ['invention_ohms_law'],
    createdAt: '1827-05-12T09:00:00.000Z',
    comments: [
      {
        id: 'post_20_comment_1',
        authorId: 'kirchhoff',
        content: '有了你的定律，我来补两条网络规则，复杂电路也能解。',
        createdAt: '1827-05-12T09:30:00.000Z',
      },
      {
        id: 'post_20_comment_2',
        authorId: 'power_electronics',
        content: '直到今天做开关电源，我也还在用这条基础关系。',
        createdAt: '1827-05-12T10:10:00.000Z',
      },
      {
        id: 'post_20_comment_3',
        authorId: 'student_user',
        content: '终于知道实验报告里为什么总在算 I=U/R 了。',
        createdAt: '1827-05-12T10:45:00.000Z',
      },
      {
        id: 'post_20_comment_4',
        authorId: 'modern_student_xiaoming',
        content: '这条定律简直是电路课“开场主角”。',
        createdAt: '1827-05-12T11:20:00.000Z',
      },
    ],
  },
  {
    id: 'post_21',
    authorId: 'kirchhoff',
    authorName: '基尔霍夫',
    verifiedLabel: '电路定律奠基人',
    yearLabel: '1845',
    yearSort: 1845,
    title: '复杂电路也有秩序：我提出了两条网络定律',
    content: `很多同学问我：如果电路不再是一根电阻和一个电源，而是“网状结构”，该怎么分析？我给出两条核心规则。第一，节点电流守恒：流入一个节点的电流总和等于流出节点的电流总和。第二，回路电压守恒：沿任一闭合回路，电压升降代数和为零。它们分别来自电荷守恒和能量守恒。

这两条定律让网络电路从“看图猜结果”变成“列方程求解”。从配电网潮流计算，到模拟电路偏置设计，再到芯片级电源网络校核，都在用同样思想。你可以把欧姆定律看作元件级关系，而基尔霍夫定律则是系统级连接规则。两者结合，电路工程第一次真正具备了规模化设计能力。`,
    researchSteps: [
      {
        title: '灵感由来',
        content:
          '欧姆定律解决了单元件关系，但真实工程是网络系统。我要找到一组与拓扑无关、可普适应用的网络规则。',
      },
      {
        title: '研究思路',
        content:
          '从守恒定律出发而不是从器件细节出发：节点上看电荷守恒，闭合回路上看能量守恒，以此建立通用方程。',
      },
      {
        title: '实验内容',
        content:
          '在多节点、多回路电路中实测支路电流与元件电压，分别验证“节点流入=流出”“回路升压=降压”。',
      },
      {
        title: '实验方法',
        content:
          '使用统一参考方向先定义各支路电流和回路方向，再把测量值带符号写入方程。方向定义可任意，但必须全程一致。',
      },
      {
        title: '结论得出',
        content:
          '任意网络电路都可用 KCL 与 KVL 建立线性方程组求解。电路分析由此进入可算法化阶段，复杂系统可计算可验证。',
      },
    ],
    formulaDerivations: [
      {
        name: '节点电流定律（KCL）',
        expression:
          '流入节点的电流总和等于流出节点的电流总和；按统一方向带符号求和时，节点电流代数和为零。',
        derivation:
          '节点处不蓄积净电荷，则单位时间流入与流出电荷量必须相等。按约定方向带符号求和，得到任意节点电流代数和为零。',
        note: '用于建立节点方程，是电网潮流与芯片电源网络分析基础。',
      },
      {
        name: '回路电压定律（KVL）',
        expression: '沿任一闭合回路，电压升高与电压降低的总和相互抵消，代数和为零。',
        derivation:
          '沿闭合回路移动时，电场做功与耗能元件压降满足能量守恒。把回路中每段电压按方向带符号相加，代数和为零。',
        note: '用于建立回路方程，配合欧姆定律可系统求解复杂网络。',
      },
    ],
    tags: ['#基尔霍夫定律', '#KCL', '#KVL', '#网络电路'],
    likes: 846,
    commentsCount: 4,
    reposts: 182,
    favorites: 571,
    relatedInventionIds: ['invention_kirchhoff_laws'],
    createdAt: '1845-09-02T08:20:00.000Z',
    comments: [
      {
        id: 'post_21_comment_1',
        authorId: 'ohm',
        content: '元件关系 + 网络规则，电路分析工具箱齐了。',
        createdAt: '1845-09-02T08:50:00.000Z',
      },
      {
        id: 'post_21_comment_2',
        authorId: 'integrated_circuit_ic',
        content: '芯片内部电源网络分析，也离不开这两条。',
        createdAt: '1845-09-02T09:20:00.000Z',
      },
      {
        id: 'post_21_comment_3',
        authorId: 'ta_assistant',
        content: '课堂提醒：列方程前先定义电流方向，别自己把自己绕晕。',
        createdAt: '1845-09-02T10:00:00.000Z',
      },
      {
        id: 'post_21_comment_4',
        authorId: 'student_user',
        content: '懂了，难怪电路题最后都是方程组。',
        createdAt: '1845-09-02T10:35:00.000Z',
      },
    ],
  },
  {
    id: 'post_22',
    authorId: 'siemens',
    authorName: '西门子',
    verifiedLabel: '发电机工程化推动者',
    yearLabel: '1866',
    yearSort: 1866,
    title: '自激式发电机落地，稳定供电更接近工业现实',
    content: `今天我们在工程侧推进了一步关键改进：自激式发电机。此前许多方案依赖外部励磁，系统复杂且运行稳定性受限。自激思路利用机器自身输出逐步建立磁场，使设备在实际工况下更容易启动和维持稳定。

对实验室来说，这或许只是“结构优化”；但对工厂和城市来说，这是可靠性与可维护性的提升。设备可持续运行、维护策略更清晰，电力开始摆脱“演示级”装置，走向“可长期服务”的基础设施。电气工程真正改变社会，靠的从来不只是理论突破，还要把方案做成能长期跑、跑得稳、可复制的大系统。`,
    tags: ['#发电机', '#自激式发电机', '#工程化', '#可靠供电'],
    likes: 873,
    commentsCount: 4,
    reposts: 188,
    favorites: 592,
    relatedInventionIds: ['invention_self_excited_dynamo', 'invention_generator'],
    createdAt: '1866-01-18T10:30:00.000Z',
    comments: [
      {
        id: 'post_22_comment_1',
        authorId: 'faraday',
        content: '看到理论走到稳定工程，真的很欣慰。',
        createdAt: '1866-01-18T11:00:00.000Z',
      },
      {
        id: 'post_22_comment_2',
        authorId: 'westinghouse',
        content: '这类工程化能力，是后面大电站的前置条件。',
        createdAt: '1866-01-18T11:40:00.000Z',
      },
      {
        id: 'post_22_comment_3',
        authorId: 'modern_factory',
        content: '系统稳定这件事，生产线真的会“用脚投票”。',
        createdAt: '1866-01-18T12:10:00.000Z',
      },
      {
        id: 'post_22_comment_4',
        authorId: 'motor',
        content: '电源稳了，我转得也更安心。',
        createdAt: '1866-01-18T12:50:00.000Z',
      },
    ],
  },
  {
    id: 'post_23',
    authorId: 'shannon',
    authorName: '香农',
    verifiedLabel: '信息论奠基人',
    yearLabel: '1948',
    yearSort: 1948,
    title: '信息可以被度量：我用“比特”重写通信问题',
    content: `在通信系统里，我们长期关心“信号能不能传过去”，但我想再往前一步：信息本身是否可以像能量一样被定量分析？今天我给出一个统一框架，引入信息熵来刻画不确定性，引入信道容量来描述在噪声条件下可可靠传输的信息上限。

这意味着通信工程从“经验调参”走向“理论上限可计算”。编码、压缩、纠错不再是零散技巧，而是围绕容量极限组织的系统设计。无线通信、光纤、卫星链路、数据中心网络，以及今天每一次视频通话和文件下载，都在沿着这个框架优化。电气工程在这里与数学和计算机深度融合，信息时代的地基由此被夯实。`,
    tags: ['#信息论', '#比特', '#信道容量', '#通信工程'],
    likes: 1186,
    commentsCount: 4,
    reposts: 276,
    favorites: 864,
    relatedInventionIds: ['invention_information_theory'],
    createdAt: '1948-07-01T09:40:00.000Z',
    comments: [
      {
        id: 'post_23_comment_1',
        authorId: 'bell_labs',
        content: '这套框架直接改变了我们做通信系统的方式。',
        createdAt: '1948-07-01T10:10:00.000Z',
      },
      {
        id: 'post_23_comment_2',
        authorId: 'wireless_comm',
        content: '从此“能不能发”变成“最多能发多少且多可靠”。',
        createdAt: '1948-07-01T10:45:00.000Z',
      },
      {
        id: 'post_23_comment_3',
        authorId: 'cpu',
        content: '编码和纠错这块，我已经准备好多线程开工。',
        createdAt: '1948-07-01T11:20:00.000Z',
      },
      {
        id: 'post_23_comment_4',
        authorId: 'student_user',
        content: '原来“网速不够”背后还有理论上限这回事。',
        createdAt: '1948-07-01T12:00:00.000Z',
      },
    ],
  },
  {
    id: 'post_24',
    authorId: 'arpanet',
    authorName: 'ARPANET',
    verifiedLabel: '互联网先驱网络',
    yearLabel: '1969',
    yearSort: 1969,
    title: '我把远方计算机连成了网：分组交换开始实战',
    content: `今天的里程碑不是“单机更快”，而是“多机互联”。我们用分组交换思路，把消息切成小数据包在网络中转发，不再依赖传统电路交换的固定专线。这样做的好处是链路利用率更高、网络弹性更强，出现故障时也更容易绕行。

它看起来像通信网络的小改进，实际却重塑了计算机系统边界：资源可以共享，任务可以远程调用，知识可以跨机构流动。后来的互联网、云计算、远程协作平台，都在这个思路上演化。电气与电子工程在“连通性”这一维度上，再次改变了社会组织方式。`,
    tags: ['#ARPANET', '#分组交换', '#计算机网络', '#互联网起点'],
    likes: 1068,
    commentsCount: 4,
    reposts: 243,
    favorites: 768,
    relatedInventionIds: ['invention_arpanet', 'invention_information_theory'],
    createdAt: '1969-10-29T21:00:00.000Z',
    comments: [
      {
        id: 'post_24_comment_1',
        authorId: 'shannon',
        content: '理论在网络实践里落地，这一幕我等很久了。',
        createdAt: '1969-10-29T21:35:00.000Z',
      },
      {
        id: 'post_24_comment_2',
        authorId: 'smartphone_modern',
        content: '今天的我能随时联网，得给你鞠一躬。',
        createdAt: '1969-10-29T22:05:00.000Z',
      },
      {
        id: 'post_24_comment_3',
        authorId: 'smart_grid',
        content: '我做实时调度也离不开稳定通信网络。',
        createdAt: '1969-10-29T22:40:00.000Z',
      },
      {
        id: 'post_24_comment_4',
        authorId: 'modern_student_xiaoming',
        content: '从“发送第一条消息”到今天全网在线，太酷了。',
        createdAt: '1969-10-29T23:10:00.000Z',
      },
    ],
  },
  {
    id: 'post_25',
    authorId: 'lithium_battery_modern',
    authorName: '现代锂电池',
    verifiedLabel: '现代储能设备',
    yearLabel: '1991',
    yearSort: 1991,
    title: '高能量密度电池量产，移动设备和电动车迎来加速期',
    content: `今天可以把一个长期目标说得更明确了：高能量密度、可重复充放电的锂离子电池开始走向规模化应用。相比早期可充电方案，它在体积能量密度、循环寿命和系统可维护性上都有明显优势，这使“便携电子设备”从短时尝鲜走向全天可用。

更重要的是，它把储能从“附件”变成“系统核心”：手机、笔记本、无人机、电动汽车、储能电站都开始围绕电池管理来设计。热管理、BMS、充放电策略、安全冗余和回收体系，成为电气工程的新战场。储能一旦进步，发电、用电、交通和电网调度都会一起被重塑。`,
    tags: ['#锂离子电池', '#储能', '#BMS', '#电动汽车'],
    likes: 1215,
    commentsCount: 4,
    reposts: 292,
    favorites: 901,
    relatedInventionIds: ['invention_lithium_ion_battery', 'invention_smart_grid'],
    createdAt: '1991-06-01T09:30:00.000Z',
    comments: [
      {
        id: 'post_25_comment_1',
        authorId: 'volta',
        content: '从电堆到今天，你们把“可持续供电”做到了新高度。',
        createdAt: '1991-06-01T10:00:00.000Z',
      },
      {
        id: 'post_25_comment_2',
        authorId: 'ev_vehicle',
        content: '续航、快充、热管理，都是我的生命线。',
        createdAt: '1991-06-01T10:40:00.000Z',
      },
      {
        id: 'post_25_comment_3',
        authorId: 'power_electronics',
        content: '电池和逆变器这对搭档，决定了系统体验上限。',
        createdAt: '1991-06-01T11:10:00.000Z',
      },
      {
        id: 'post_25_comment_4',
        authorId: 'electric_energy',
        content: '我终于可以被更灵活地“存起来再调用”。',
        createdAt: '1991-06-01T11:45:00.000Z',
      },
    ],
  },
  {
    id: 'post_26',
    authorId: 'hvdc_modern',
    authorName: '现代高压输电',
    verifiedLabel: '现代输电技术',
    yearLabel: '2020',
    yearSort: 2020,
    title: '特高压与柔性直流协同，跨区域绿电输送进入新阶段',
    content: `今天的电力系统面临一个新命题：新能源资源与负荷中心经常相隔上千公里。为了把风光资源高效送到城市，我们持续推进特高压交流与柔性直流工程。高电压、大容量、低损耗是关键指标，但工程挑战同样巨大：系统稳定、故障穿越、继电保护、换流控制和多端协调都必须精细设计。

这类工程的价值不只在“送得远”，更在“送得稳、送得经济、送得可持续”。当跨区输电与本地储能、需求响应、智能调度协同后，电网可以在更大范围平衡波动性新能源。电气工程在这里再次体现系统能力：从单点设备优化，升级为全国尺度的能源协同。`,
    tags: ['#特高压', '#柔性直流', '#远距离输电', '#新能源消纳'],
    likes: 1322,
    commentsCount: 4,
    reposts: 319,
    favorites: 968,
    relatedInventionIds: ['invention_hvdc_flexible_grid', 'invention_smart_grid'],
    createdAt: '2020-09-18T10:00:00.000Z',
    comments: [
      {
        id: 'post_26_comment_1',
        authorId: 'tesla',
        content: '看到“把电送到远方”这件事走到今天，我很满意。',
        createdAt: '2020-09-18T10:30:00.000Z',
      },
      {
        id: 'post_26_comment_2',
        authorId: 'smart_grid',
        content: '跨区输电 + 实时调度，是我这一代的基础能力。',
        createdAt: '2020-09-18T11:05:00.000Z',
      },
      {
        id: 'post_26_comment_3',
        authorId: 'photovoltaic',
        content: '有了高效外送通道，弃光问题真的能缓解不少。',
        createdAt: '2020-09-18T11:40:00.000Z',
      },
      {
        id: 'post_26_comment_4',
        authorId: 'modern_grid',
        content: '大范围互联之后，系统韧性也上了一个台阶。',
        createdAt: '2020-09-18T12:20:00.000Z',
      },
    ],
  },
]
